### ISSUE TITLE
external API for the uploader to scan for changes in the filesystem

### ISSUE THREAD

**Issue by vu3rdd** [LeastAuthority/magic-folder#130]
@meejah and I were chatting about Uploader and were thinking that uploader could benefit from having an explicit API to scan the filesystem for changes which could be useful for testing and for external applications like Gridsync to use.

**Comment by meejah** [comment]
Further discussion about existing user-research indicates we *might* also want a mode where the *only* way new snapshots appear is via API requests (which would be triggered by a UI/UX tool probably via user action). That could be this API. So maybe we want the API to be "check for changes to: [file0, file1]" so that a frontend tool can offer the user the chance to make new snapshots for just a single file. If the file-list is empty we could scan everything.

**Comment by meejah** [comment]
Note that the latter API exists ("make a Snapshot for this one file") and there's a PR for a CLI command to trigger it (#309)

**Comment by meejah** [comment]
There is an HTTP API to do both a local `scan` or a remote `poll`
