### ISSUE TITLE
Better handing of --web-port <number>

### ISSUE THREAD

**Issue by sajith** [LeastAuthority/magic-folder#158]
Currently running `magic-folder --node-directory nodes/alice run --web-port 6000` will print this message:

```
Traceback (most recent call last):
  File "magic-folder/venv/lib/python2.7/site-packages/twisted/application/service.py", line 288, in startService
    service.startService()
  File "magic-folder/src/magic_folder/cli.py", line 1104, in startService
    d = maybeDeferred(do_magic_folder, self.options)
  File "magic-folder/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "magic-folder/src/magic_folder/cli.py", line 1092, in do_magic_folder
    return maybeDeferred(f, so)
--- <exception caught here> ---
  File "magic-folder/venv/lib/python2.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "magic-folder/src/magic_folder/cli.py", line 621, in main
    options["web-port"],
  File "magic-folder/src/magic_folder/cli.py", line 705, in from_node_directory
    return cls(reactor, config, webport, magic_folders)
  File "<attrs generated init magic_folder.cli.MagicFolderService>", line 10, in __init__
    self.__attrs_post_init__()
  File "magic-folder/src/magic_folder/cli.py", line 671, in __attrs_post_init__
    serverFromString(self.reactor, self.webport),
  File "magic-folder/venv/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1731, in serverFromString
    nameOrPlugin, args, kw = _parseServer(description, None)
  File "magic-folder/venv/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1649, in _parseServer
    getPlugins(IStreamServerEndpointStringParser), endpointType
  File "magic-folder/venv/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1665, in _matchPluginToPrefix
    raise ValueError("Unknown endpoint type: '%s'" % (endpointType,))
exceptions.ValueError: Unknown endpoint type: '6000'
```

Perhaps adding the `tcp:` prefix to web port would be a small improvement?

**Comment by exarkun** [comment]
I'm not sure this is actually a good idea.  There's an expressive, extensible syntax for the string that goes into this place.  Rather than taking a guess about what an invalid string might mean, rejecting it seems preferable to me.  Perhaps we could reject it with more information to help the user learn what they need to supply instead?  Perhaps supplying a default value so users don't even have to supply one would be another good improvement.

**Comment by exarkun** [comment]
Here's the Twisted documentation for the feature - https://twistedmatrix.com/documents/current/core/howto/endpoints.html#clients

**Comment by meejah** [comment]
I don't think having a default is a good idea; it did have one at some point, but (I at least) found this confusing.
(Perhaps having it in the config would be a good improvement, though).

**Comment by meejah** [comment]
I'm not sure that I understand why you think this PR as it sits is a bad idea?

It's pretty common for daemons to take "a port" and pretty _un_-common for things to take a string like "tcp:1234". In this case it's really straightforward to figure out what the user means -- I would expect a ton of users will run "--web-port 1234" and then have to read the words and re-run immediately with "--web-port tcp:1234". People running this are also unlikely to know it's "a Twisted thing" (versus e.g. running it via `twist` or similar).

Didn't the Twisted `clientFromString` parser take a plain number and assume TCP at some point? (Ah, yes, seems it got removed in 8bbdf3f47d1a6e5bf614854401abed2e011e2c7f in 2016).

**Comment by exarkun** [comment]
I think it's a bad idea now because it involves guessing the user's intent but I still like the idea of "in the face of ambiguity, refuse the temptation to guess."  Right now `--web-port` takes an endpoint description string, not a TCP port number. If we think TCP port number is better, let's just change it to that and forget about endpoint description strings.  If we think we need to support both (why?) then two different options would be sensible ... eg `--web-port` and `--web-endpoint` (but why clutter the UI with two options, one of which is a complete subset of the other?)

**Comment by meejah** [comment]
Why does this count as "guessing"? If the docs say you can pass a number and then that means it's a TCP port, isn't that clear?

(I don't know have context on why it takes any endpoint string but at least that lets you choose e.g. Unix socket or Tor to listen on if you wanted)

**Comment by exarkun** [comment]
Hmm.  I say it's "guessing" because it means a string has two possible different interpretations and we can't *know* which one the user intended.  We can document our simple heuristic so that it's more likely that the user types in something that leads to the desired result.  I still want to call it guessing because there could be an endpoint plugin that makes "12345" meaningful but I suppose it isn't *really* (any more than parsing a string from a user ever is, at least) if we've explained this to the user ... and a "12345" plugin seems like it would involve some fairly dubious choices anyway...

So, more concretely, it's blocking off part of the domain of the endpoint strings.  All `s.isdigit()` strings are also possibly valid inputs to `clientFromString` but we're saying you can't access those, you get our alternate assigned meaning instead (which is already available from a different area of the endpoint strings domain).

**Comment by exarkun** [comment]
(I meant `serverFromString`, of course)

**Comment by meejah** [comment]
Ah, right, I meant `serverFromString` too ;)

However, doesn't every valid input to that function have a `:` in it?

**Comment by exarkun** [comment]
It seems like the parser is happy (well, "happy") with no `:` at all:

```
$ twist web --listen 12345:
Traceback (most recent call last):
  File "/home/exarkun/Scratch/zkapauthz/bin/twist", line 8, in <module>
    sys.exit(Twist.main())
  File "/home/exarkun/Scratch/zkapauthz/lib/python2.7/site-packages/twisted/application/twist/_twist.py", line 124, in main                                                                                       
    options=options.subOptions,
  File "/home/exarkun/Scratch/zkapauthz/lib/python2.7/site-packages/twisted/application/twist/_twist.py", line 62, in service                                                                                     
    service = plugin.makeService(options)
  File "/home/exarkun/Scratch/zkapauthz/lib/python2.7/site-packages/twisted/web/tap.py", line 314, in makeService                                                                                                 
    svc = strports.service(port, site)
  File "/home/exarkun/Scratch/zkapauthz/lib/python2.7/site-packages/twisted/application/strports.py", line 40, in service                                                                                         
    endpoints.serverFromString(reactor, description), factory)
  File "/home/exarkun/Scratch/zkapauthz/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1731, in serverFromString                                                                                
    nameOrPlugin, args, kw = _parseServer(description, None)
  File "/home/exarkun/Scratch/zkapauthz/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1649, in _parseServer                                                                                    
    getPlugins(IStreamServerEndpointStringParser), endpointType
  File "/home/exarkun/Scratch/zkapauthz/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1665, in _matchPluginToPrefix                                                                            
    raise ValueError("Unknown endpoint type: '%s'" % (endpointType,))
ValueError: Unknown endpoint type: '12345'
```

I didn't go so far as to make such a plugin and see what happens next though.  I suppose it could still blow up trying to pull arguments out of the string after it found a match.

**Comment by exarkun** [comment]
eh sorry I pasted the wrong transcript above.  It does exactly the same thing with `12345` (instead of `12345:` as I pasted)

**Comment by exarkun** [comment]
I think it probably does work.  The premise of the syntax, I am now reminded, is basically positional and keyword arguments separated by `:`.  So `foo:bar:baz=quux` parses to `("foo", "bar")` and `{"baz": "quux"}`.  `foo` parses to `("foo",)` and `{}`.

**Comment by meejah** [comment]
Isn't the "stuff before the first colon" the "kind of endpoint-parser"?

But, okay, so I guess you could register a "kind" of endpoint parser called "1234" that takes no args and so `twist` treats "1234:" the same as "1234".

**Comment by meejah** [comment]
(Pragmatically, I'm willing to take the slight risk that someone makes a parser for Twisted whose name is a number below 65536 ... but if I *had* to choose not to accept both numbers-as-ports and endpoint-strings there, I'd say that since we spelled it `--web-port` and since most people will assume it's a TCP port it should just be a port number and we can add `--web-endpoint` later if we like?)

Alternatively, what if this command-line option goes away and it's "part of the configuration"? I don't really understand how this does (or is supposed to work) .. you `magic-folder create` individual folders, but is there a step like that for "create the config to run the daemon"...?

**Comment by sajith** [comment]
Perhaps `--listen=<endpoint>` would be the right choice of name here?  To me `--web-port=` suggested that the argument is expected to be a port number.  I did not understand what "string description of an endpoint" meant, until I read the code, and even then I expected that port could be a number.

We could handle the error and print some expanded help text when an incorrect argument is provided?

Although I think it would be a reasonable expectation that if the program can handle `--web-port tcp:8000` it should also handle `--web-port 8000`.  Why should a human do a computer's job? :^)

**Comment by exarkun** [comment]
> Pragmatically, I'm willing to take the slight risk that someone makes a parser for Twisted whose name is a number below 65536 

I agree that the scope for harm here is pretty small.  I don't really want to argue against this very hard except it *does* seem like a bad idea to me and "at least it can't cause much harm" is a hard motivation to rally behind. :)

> Alternatively, what if this command-line option goes away and it's "part of the configuration"? I don't really understand how this does (or is supposed to work) .. you magic-folder create individual folders, but is there a step like that for "create the config to run the daemon"...?

Yea, ehm... There isn't really really any existing non-command-line configuration needed to run the daemon, I think?  It piggy-backs on magic_folders.yaml from the Tahoe-LAFS node directory and requires the HTTP server port number on the CLI.  There isn't anything else right now.

Perhaps in the future `magic_folders.yaml` can grow to be able to express more things (eg the web endpoint)?  It looks like there's room as a sibling of the `magic-folders` top-level key, I suppose.  I'm not a *complete* fan of "just supply an arbitrarily complex data structure as a yaml file to configure your application" but it is clearly a widespread pattern...

One thing to bear in mind is that `magic-folder run ...` was not necessarily a carefully designed user interface.  It is more the case that it is the shape of the thing that was carved out of the Tahoe-LAFS CLI which most people agree is clunky and difficult to use.  Maybe the UI/UX problems here are deeper than the question of whether a user types "xxx" or "tcp:xxx" into one argv slot.

Here's a question.  Who is `magic-folder run` *for*?  How can that user be best served?

> Perhaps --listen=<endpoint> would be the right choice of name here?

Turns out `--listen` is exactly what `twist web` calls it, though the other Twisted CLI interfaces mostly pick their own random names (including `--port`).

**Comment by meejah** [comment]
> Yea, ehm... There isn't really really any existing non-command-line configuration needed to run the daemon, I think? It piggy-backs on magic_folders.yaml from the Tahoe-LAFS node directory and requires the HTTP server port number on the CLI. There isn't anything else right now.

"All magic-folder's config" is in the tahoe node-dir, yes. So there's `magic-folders.yaml` there's possibly stuff in `tahoe.cfg`, there's a magic-folder DB per magic folder and the author private-keys (also per-magic-folder). So, plenty of "configuration" piled in there. Maybe that should all be in its own place -- but also what's wrong with "one more thing" being in there somewhere?

We could certainly put it in `magic-folders.yaml` because the actual "magic folders" information is in a "`magic-folders:`" heading (dict? I don't know what yaml calls this) so there could be an "api" or "daemon" or something in there too. We also need an API token (again, this will currently just come from Tahoe's `api_auth.token` but then we're using the same token for two different daemons).

**Comment by exarkun** [comment]
> but also what's wrong with "one more thing" being in there somewhere?

Not sure I'd really argue strongly against this yet but I think the rest of what you pointed out is arguably internal state, not configuration (or we want to *make* it thus).  We don't want people editing `magic-folders.yaml` right?  We want them using the CLI or the HTTP API.  Because we don't want to have to think about what the users will think if we want to change `magic-folders.yaml` somehow.

It's true that possibly there is tahoe.cfg stuff but I think we should run away from that as quickly as we can.  It's all the magic-folder stuff that's old and out of favor even when magic-folder was part of Tahoe-LAFS.

So I guess we should figure out if we're committed to having user-editable configuration files for magic-folder or not.  I think "not" is a better choice - but it does deny us the option of telling users to write this into a file somewhere instead of supplying it on the CLI.

**Comment by meejah** [comment]
Yes, we don't want users mucking around in there. So `magic-folder migrate` would need to grow an argument for "the listening endpoint". Do we have a command for "create a magic-folder daemon" distinct from "add another magic-folder to my daemon"..?

Personally, I like the idea that you use the CLI to change stuff, period (whether that's "config" or "state", meh). I guess that implies some sort of "change the web-port, or other things" command? At least with this setup users don't have to apprehend the full horror of "the tahoe node-dir" and we can (incrementally) change where things are stored.

This means it's more of a one-time thing so I guess going through the re-discovery of "oh right, it won't take a port-number" is at least minimized.

Only quasi-related, but since we agree that the API can expose private data (because you always need the token) most magic-folder CLI commands should just be wrappers over calling an API and so then "real" front-ends like GridSync can also use it to change configuration.

**Comment by exarkun** [comment]
> Personally, I like the idea that you use the CLI to change stuff, period

+1

> (whether that's "config" or "state", meh).

The only important distinction I can think of here right now is that if I give a system some config, that's the config.  It should not decide on its own to change this, in general.  Config is part of the system's state, I guess, but the *rest* of the system's state is free to change however the system wants in delivering its service.

So, for example, if I tell magic-folder to listen on tcp:12345 and tcp:12345 is already in use, magic-folder is not free to listen on tcp:12346 instead.  That's config.

> I guess that implies some sort of "change the web-port, or other things" command?

Yea, I suppose it must.  Are we thinking along the lines of `git config` here, then?

> At least with this setup users don't have to apprehend the full horror of "the tahoe node-dir" and we can (incrementally) change where things are stored.

+1

> This means it's more of a one-time thing so I guess going through the re-discovery of "oh right, it won't take a port-number" is at least minimized.

As long as your memory is good enough. :)  I think we can streamline this learning process a lot compared to the current experience though ... give some examples, give a better error message, etc.

> Only quasi-related, but since we agree that the API can expose private data (because you always need the token) most magic-folder CLI commands should just be wrappers over calling an API and so then "real" front-ends like GridSync can also use it to change configuration.

Yes, absolutely this.  And I think the CLI should really literally just call the (HTTP) API so there's no difference at all between the CLI and some other frontend doing it - eg if we decide that reconfiguring the listening port takes effect immediately at runtime in the running process, this should be true whether GridSync or the CLI does it (and more usefully, if you add a new magic-folder to the config, that should be able to affect the running process as well).

**Comment by meejah** [comment]
Sounds good. I was waffling with "most CLI commands" because at least "magic-folder run" or so won't have an API equivalent.

**Comment by meejah** [comment]
This seems obsolete (and unlikely to reach a conclusion anyway).
