### ISSUE TITLE
The `/api` endpoint returns a JSON Array

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#174]
This is a risky practice with a history of being a component of vulnerabilities.

The endpoint returns a resource like:

```
[{"status": "failed", "kind": "upload", "failure_at": 1593715542.451954, "failed_at": 1593715542.452227, "path": "g", "percent_done": 100.0, "started_at": 1593715540.705583, "queued_at": 1593715540.700779, "size": 1048576}]
```

Read about the problems with returning an Array at https://blog.jeremiahgrossman.com/2006/01/advanced-web-attack-techniques-using.html and https://haacked.com/archive/2009/06/25/json-hijacking.aspx/

**Comment by meejah** [comment]
Why did this end up at `/api` anyway? This looks like the tahoe-lafs "magic-folder status" API..? 

Anyway, presumably this will "go away" because I thought we'd decided that the way Tahoe's web-token thing works is bad (because it is `POST`-only). Still, interesting/good to note those vulnerabilities. I don't think they apply to this API, though, since the goal is to disallow browsers using it at all (that is, you need to "do a thing with a token you got from the filesystem" to access any of the API) and both are browser problems (from my quick reading).

**Comment by exarkun** [comment]
> Anyway, presumably this will "go away" because I thought we'd decided that the way Tahoe's web-token thing works is bad (because it is POST-only). 

Yes, I hope so.  Today @vu3rdd and I worked on the first new endpoint and it's not going to be in this same hierarchy or do the things that we don't like about how this one works.

**Comment by meejah** [comment]
Cool. The "new way" we decided was simply to pass the token-stuff in a header instead of a POST-arg right?

**Comment by exarkun** [comment]
I think we did (though I don't see this noted in the design doc right now).  @vu3rdd and I started implementing something assuming we'd use the "Bearer token" flavor of the "Authorization" header (introduced, I guess, but the OAuth 2 RFC).  These are almost exactly the same as "Basic" but without the implied username/password and without mandatory base64 encoding.

**Comment by meejah** [comment]
Does this imply that you *can't* do the same trick with dicts? (Anyway, browsers can't be consuming this API at all, right?)

**Comment by exarkun** [comment]
It is apparently true that you can't do the same trick with dicts - which is to say "objects", of course.  My understanding is that Array is vulnerable because an Array display (or whatever it is called, dunno - I mean `[1, 2, 3]`) is legal JavaScript so browsers choose (or chose in the past?) to evaluate it as JavaScript and thus an alternate Array prototype might get evaluated whereas an object display (again, whatever - I mean `{a: b}`) cannot be legal JavaScript so browsers choose (/chose) to parse it as JSON and never evaluate it as JavaScript so the Object prototype is irrelevant.  I hope I summarized all of that right.  If it seems wrong, maybe I didn't and I'll direct you at the original writeups linked above. :)

**Comment by meejah** [comment]
As for this bug, the relevant part seems to be "will browsers EVER consume this API?" because this is just a browser problem (and so far as I know we don't have plans to let a browser consume this API as it exists). Perhaps that should be documented in the API more explicitly (with reference to this particular problem).

....and anyway, does wrapping it in a dict/object help at all? Like, if I have `{foo: [1, 2, 3]}` does the `Array`-prototype hack described still function (on the `[1, 2, 3]` piece)?

Since we're already depending on "only apps which can access a file can use this API" I think we should simply formalize that and in the future we could introduce a "browser sanitized" version of the API for any future browser-based JS access we might wish to allow.

**Comment by exarkun** [comment]
> As for this bug, the relevant part seems to be "will browsers EVER consume this API?" because this is just a browser problem (and so far as I know we don't have plans to let a browser consume this API as it exists). Perhaps that should be documented in the API more explicitly (with reference to this particular problem).

I guess the challenge there is that it's tough to make predictions, especially about the future.  Considering how easy it is to avoid this particular pitfall (for new APIs), it seems worth doing, even if there's no clear path from where we are to having a browser consume this.

> ....and anyway, does wrapping it in a dict/object help at all? Like, if I have {foo: [1, 2, 3]} does the Array-prototype hack described still function (on the [1, 2, 3] piece)?

Apparently it does help because once you trick the browser into using a real JSON parser with `{` then it's JSON parsing all the way down.

Also it's possible this is largely or completely historical.  The referenced blog posts are over ten years old, after all.  But again, easy to avoid, so why not avoid it?

> I think we should simply formalize that and in the future we could introduce a "browser sanitized" version of the API for any future browser-based JS access we might wish to allow.

I think the idea of an API that is actually *for* browsers is good and fine.  I still think it's worth avoiding this pitfall for the non-browser API because we can't *stop* any browser from hitting our endpoints.  They shouldn't have the necessary credentials to actually make them work but it's a bit hard to be completely sure of that too (esp. if we consider browsers of the future may be different, perhaps they have built-in support for bearer tokens or something).

**Comment by meejah** [comment]
>  I still think it's worth avoiding this pitfall for the non-browser API because we can't stop any browser from hitting our endpoints.

Yes we can (that's the whole point of the token thing, right?). If we *can't* prevent browsers from accessing this API then we need to re-think the whole approach (because we don't want random JS on the internet accessing people's magic-folder instances).

**Comment by meejah** [comment]
(That last comment isn't meant to completely dismiss this; maybe "always return a dict" is a good rule ... but browsers should definitely NOT have access to this API)

**Comment by exarkun** [comment]
> Yes we can (that's the whole point of the token thing, right?). 

Sorry, to be clear, I meant we can't stop random web apps from issuing a request with this path.  I think we can do a pretty good job making sure those requests receive an UNAUTHORIZED response with the token, for sure.  I counted this as "hitting our endpoints" but it certainly doesn't mean browsers can access the actual resource.

Also I *guess* even without the tokens browsers can't use any response we return because ... CORS?  I am definitely no expert on browser security I just have some ideas about what some of the pieces are.

Until this comment I had forgotten about CORS entirely, in fact, and its existence seems to strengthen the argument that a it is very unlikely a browser will ever be able to get non-error responses for any of our endpoints.

**Comment by meejah** [comment]
Okay, so, yes: a browser can make a _request_ to `localhost:1234` but it can't read the response "because CORS". CORS is about granting more permissions (so if we don't send CORS headers then a browser-request can't -- I don't _**think**_ -- ever read the response).

I don't know that I ever had enough knowledge of "same origin policy" to know when it does (or more importantly *doesn't* apply) but so long as everything NEEDS the token to get any response besides "error" I think we're safe. (I'm pretty sure that if you load "file:///" then "localhost" counts as "same origin" .. maybe that leads to some kind of attack if you can get a user to download and then view a local file?)

Still could be a good idea to say "all JSON responses must be `dict`s..?

**Comment by exarkun** [comment]
We went ahead and deleted the `/api` endpoint so all we really have to do now is always return objects instead of arrays in all future endpoints...
