### ISSUE TITLE
Errors from LocalSnapshotCreator.process_item are logged but otherwise not acted upon

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#220]
See `LocalSnapshotService._process_queue`.

If processing an item fails - for example, if permission is denied, there is some other I/O error, there is some error loading information from the database, etc - the exception will be logged but nothing else is done.

This will leave the Deferred returned by `add_file` hanging indefinitely so application code there has no chance to react.  This also means the item itself is unprocessed and will never be processed (if the error was transient then a retry could eventually succeed).

Also, the exception is currently double-logged.  Once as the failure reason for the PROCESS_FILE_QUEUE action and once by the explicit `write_traceback`.

**Comment by meejah** [comment]
This is somewhat obsolete -- and maybe should just be closed with a different ticket describing any missing functionality.

The `Deferred` will not be dropped anymore. Ultimately, an error will come out of the public API `MagicFolder.add_snapshot()`. Any such error will thus make it to the Web API or the CLI depending how `add_snapshot()` was called.

There isn't any built-in retry logic (although it's also not clear if that's a good idea). For example, something using the Web API probably _does_ want to get a "disk full" error instead of having the application continuously re-trying and failing.

If there are errors we'd like to handle differently, separate tickets are more appropriate.
