### ISSUE TITLE
Add "pre-commit" flake8 hook

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#289]
https://pre-commit.com/ is a project to glue checks into the git pre-commit hook system.  It is a handy way to do things like run flake8 prior to every commit.  The motivation here is similar to the motivation for systems like emacs' flycheck - learn about errors early.  The idea is not to replace CI but to learn about problems that CI will eventually find but only after much more time has passed.

**Comment by meejah** [comment]
(I put this in a review comment, but maybe it's better here): I think it would be better to configure flake8 etc as "push" hooks -- I often have commits that are "a chunk of stuff that does something" but aren't necessarily "ready" in any sense. Or, sometimes I will commit everything that's currently in-progress on a branch because i want to move on to something else (and stashes tend to .. get lost).

But also maybe I don't know how hooks work; I assume the pre-commit hooks prevent commits from happening at all if the hook exits non-zero?

**Comment by exarkun** [comment]
After some practical experience with pre-commit on Tahoe-LAFS I'm not interested in this anymore.
