### ISSUE TITLE
Consider whether the magic-folder `api_client_endpoint` should be in the global config database.

### ISSUE THREAD

**Issue by tomprince** [LeastAuthority/magic-folder#339]
Having it there requires anything interacting with magic-folder to open the entire config, rather than just enough information to connect to the server.

**Comment by meejah** [comment]
At some point we had decided that "all config shall go in the database".  Perhaps this is the exception that that rule ;)

As a workaround for right now, there is `magic-folder show-config` that spits out JSON (e.g. for clients that aren't "the CLI"). For users like GridSync it should "just know" the endpoint because it called `magic-folder init` in the first place.

I suppose, though, that the point of this ticket is for non-Python, non-magic-folder clients; it could indeed be a nice convenience to have a file that indicates the current endpoint as well.

**Comment by tomprince** [comment]
Conceptually, the api client endpoint is config that is being published by the service, instead of consumed, so I think it reasonable to treat it differently than the rest of the config, which the service consumes.
