### ISSUE TITLE
Remove "connected enough" code

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#397]
At startup, `magic-folders` tries to check if its tahoe node is "connected enough" to do work. This means importing `allmydata` libraries to load Tahoe config to find out what "shares_needed" etc are. Perhaps this made sense when magic-folders was a tahoe subcommand but it doesn't necessarily make sense for standalone magic-folders.

It also means an extra `allmydata` import.

We do have to handle the case when Tahoe operations fail (whether we're "connected enough" or not). Obviously, those connections could go away at any time so checking up front doesn't really help or make sense.

**Comment by tomprince** [comment]
While we do need to handle the case when tahoe operations fail, it may be worth getting the information from tahoe (though it would be preferable to change tahoe to expose the information via the web interface), so we can report more accurate status to gridsync.

For example, if the node is not connected to any storage servers, we won't ever be *actually* uploading.

I also wonder if https://tahoe-lafs.org/trac/tahoe-lafs/ticket/232 might be a related issue that we should be wary of triggering.

**Comment by meejah** [comment]
If it's not uploading, the `tahoe put` should fail (and thus we'll report that we aren't actually uploading).

**Comment by tomprince** [comment]
> I also wonder if https://tahoe-lafs.org/trac/tahoe-lafs/ticket/232 might be a related issue that we should be wary of triggering.

Doing some history diving, it looks like the check was added in https://tahoe-lafs.org/trac/tahoe-lafs/ticket/1449 to address exactly this type of issue.

I actually wonder if (until the [upstream bug](https://tahoe-lafs.org/trac/tahoe-lafs/ticket/1057) is fixed), it would make sense to do this check whenever we are updating a mutable directory, instead of checking once at startup.

> It also means an extra allmydata import.

We could instead use configparser to read `tahoe.cfg` directly. (Looking at the tahoe code, it looks like the only thing extra it does beyond call configparser is validate the file.

> If it's not uploading to enough servers to be "happy" then the tahoe put should fail (and thus we'll report that we aren't actually uploading).

My understanding is that mutable files don't support happiness yet, though.

**Comment by meejah** [comment]
Mutables have a different notion of happiness than immutables, yes.
