### ISSUE TITLE
Newly-added magic-folders consistently fail to upload their contents upon being added

### ISSUE THREAD

**Issue by crwood** [LeastAuthority/magic-folder#513]
I'm trying to add a directory of Cat Pictures to a storage grid using Magic-Folder. Upon adding the directory as a new magic-folder, I observe that the files are immediately inserted into the `uploads` queue (as per the websocket/"status" API message I receive), for example:

```
{"state": {"folders": {"Cat Pics": {"downloads": {}, "errors": [], "uploads": {"Garfield.jpg": {"queued_at": 1627490579.161172, "name": "Garfield.jpg"}, "Cheshire Cat.jpeg": {"queued_at": 1627490579.197408, "name": "Cheshire Cat.jpeg"}, "Kitler.png": {"queued_at": 1627490579.275344, "name": "Kitler.png"}, "Colonel Meow.jpg": {"queued_at": 1627490579.212371, "name": "Colonel Meow.jpg"}, "Nala.jpg": {"queued_at": 1627490579.119796, "name": "Nala.jpg"}, "hi": {"queued_at": 1627490579.226819, "name": "hi"}, "Waffles.jpg": {"queued_at": 1627490579.241689, "name": "Waffles.jpg"}, "Venus.jpg": {"queued_at": 1627490579.132815, "name": "Venus.jpg"}, "Grumpy Cat.jpg": {"queued_at": 1627490579.260308, "name": "Grumpy Cat.jpg"}, "lolcat.jpg": {"queued_at": 1627490579.186279, "name": "lolcat.jpg"}, "empty": {"queued_at": 1627490579.150049, "name": "empty"}}, "recent": [{"empty": {"modified": 1627332466, "last-updated": 1627490579}}, {"Venus.jpg": {"modified": 1627332237, "last-updated": 1627490579}}, {"Grumpy Cat.jpg": {"modified": 1627328132, "last-updated": 1627490579}}, {"Garfield.jpg": {"modified": 1627317666, "last-updated": 1627490579}}, {"Nala.jpg": {"modified": 1589853198, "last-updated": 1627490579}}, {"lolcat.jpg": {"modified": 1589853198, "last-updated": 1627490579}}, {"Cheshire Cat.jpeg": {"modified": 1589853198, "last-updated": 1627490579}}, {"Colonel Meow.jpg": {"modified": 1589853198, "last-updated": 1627490579}}, {"hi": {"modified": 1589853198, "last-updated": 1627490579}}, {"Waffles.jpg": {"modified": 1589853198, "last-updated": 1627490579}}]}}, "synchronizing": true}}
```

As a user (or consumer of this status API), I would expect these `uploads` entries to immediately begin to upload (one at a time, serially, given Magic-Folder's known/current lack of parallel upload support), however, as per the information provided by status API alone, nothing appears to happen; it isn't until ~60 seconds later that I'm able to observe the `uploads` entries gradually beginning to disappear, one at a time, from the status API output (presumably, because they are successfully uploaded to the grid). Surprisingly, adjusting the `scan-interval` appears to make no difference here; newly-added folders consistently leave a ~60 second delay between a) the time that a new magic-folder is added and b) the time that the files within that folder begin to upload to the grid.

Looking at Magic-Folder's [eliot log output](https://github.com/LeastAuthority/magic-folder/files/6895193/mf.log), I see that there is an uncaught `KeyError` thrown for each file within the directory, observed immediately after the folder is added -- here's a snippet:

```
792ae7f1-5e57-49c7-8cfc-b8eddf716566
└── config:state-db:get-remote-snapshot-entry/1 ⇒ started 2021-07-28 16:42:59Z ⧖ 0.000s
    ├── relpath: Garfield.jpg
    └── config:state-db:get-remote-snapshot-entry/2 ⇒ failed 2021-07-28 16:42:59Z
        ├── exception: exceptions.KeyError
        └── reason: u'Garfield.jpg'

0deadb3b-35fa-472f-83ce-9fbae66cbe54
└── magic-folder:local-snapshot-creator:process-queue/1 ⇒ started 2021-07-28 16:42:59Z ⧖ 0.017s
    ├── relpath: /home/user/Cat Pics/Garfield.jpg
    ├── config:state-db:get-remote-snapshot-entry/2/1 ⇒ started 2021-07-28 16:42:59Z ⧖ 0.000s
    │   ├── relpath: Garfield.jpg
    │   └── config:state-db:get-remote-snapshot-entry/2/2 ⇒ failed 2021-07-28 16:42:59Z
    │       ├── exception: exceptions.KeyError
    │       └── reason: u'Garfield.jpg'
    ├── magic-folder:local-snapshot-creator:processing-item/3/1 ⇒ started 2021-07-28 16:42:59Z ⧖ 0.017s
    │   ├── relpath: Garfield.jpg
    │   ├── config:state-db:update-snapshot-entry/3/2/1 ⇒ started 2021-07-28 16:42:59Z ⧖ 0.000s
    │   │   ├── relpath: Garfield.jpg
    │   │   └── config:state-db:update-snapshot-entry/3/2/2 ⇒ succeeded 2021-07-28 16:42:59Z
    │   │       └── insert_or_update: insert
    │   └── magic-folder:local-snapshot-creator:processing-item/3/3 ⇒ succeeded 2021-07-28 16:42:59Z
    └── magic-folder:local-snapshot-creator:process-queue/4 ⇒ succeeded 2021-07-28 16:42:59Z

```
It isn't until ~60 seconds later -- at `16:_43_:59` in the logs -- that I see a successful snapshot/upload:

```
b40476e4-63f5-4ffd-b724-9f687586a877
└── magic-folder:uploader-service:upload-local-snapshot/1 ⇒ started 2021-07-28 16:43:59Z ⧖ 1.932s
    ├── relpath: Garfield.jpg
    ├── snapshot:metadata/2 2021-07-28 16:44:00Z
    │   ├── capability: URI:DIR2-CHK:ukldp3qsugsovnumgj5blnduau:bslevr62nchty4yyg52ea6dkmcjlqt55xt4prajhka5odfjbjmfq:1:1:419
    │   ├── metadata: 
    │   │   ├── author: 
    │   │   │   ├── name: admin
    │   │   │   └── verify_key: Yw7mKIiRYlC0DwtkCsAIIqCsBuvwKJTY1/m4UXbEeDE=
    │   │   ├── modification_time: 1627317666
    │   │   ├── name: Garfield.jpg
    │   │   ├── parents: 
    │   │   └── snapshot_version: 1
    │   └── name: Garfield.jpg
    ├── config:state-db:update-snapshot-entry/3/1 ⇒ started 2021-07-28 16:44:00Z ⧖ 0.000s
    │   ├── relpath: Garfield.jpg
    │   └── config:state-db:update-snapshot-entry/3/2 ⇒ succeeded 2021-07-28 16:44:00Z
    │       └── insert_or_update: update
    ├── config:state-db:delete-local-snapshot-entry/4/1 ⇒ started 2021-07-28 16:44:01Z ⧖ 0.000s
    │   ├── relpath: Garfield.jpg
    │   └── config:state-db:delete-local-snapshot-entry/4/2 ⇒ succeeded 2021-07-28 16:44:01Z
    └── magic-folder:uploader-service:upload-local-snapshot/5 ⇒ succeeded 2021-07-28 16:44:01Z
```

Presumably this behavior is not intentional and the uncaught `KeyError` captured by the logs above is responsible for or related to the delay incurred. Users will probably expect to not have to wait one additional minute for newly-added folders to upload, in any case.

**Comment by tomprince** [comment]
That is more or less expected behavior, though perhaps not desired. We take local snapshots as we discover them, and then periodically upload them as a separate task. It looks like poll-interval currently controls how often we look for uploads to do.

Note that the `KeyError` isn't uncaught, it is the database layer reporting that we don't currently have a remote snapshot for that file (which we look for when determining the parent of the snapshot we are creating). I do agree that how the log is presented looks like it may be something failing. That `KeyError` is actually explicitly raised: https://github.com/LeastAuthority/magic-folder/blob/3222d834127f5333655d71366e4b7fea77e80dfe/src/magic_folder/config.py#L1135-L1145

**Comment by crwood** [comment]
>That is more or less expected behavior, though perhaps not desired.

"Expected" for the developers of this project, perhaps, but this behavior surely runs contrary to the expectations of end-users who have previously used any other "cloud storage" software. I suspect that no reasonable person, at least, would _want_ to wait an additional minute for their folders to upload after adding them (and that many users would, at some point during this minute-of-receiving-no-feedback, begin to think that something must have gone wrong...).

>We take local snapshots as we discover them, and then periodically upload them as a separate task. It looks like poll-interval currently controls how often we look for uploads to do.

Thank you for explaining this. I suspected that something was out of alignment with my own prior expectations regarding the functionality of [endpoint for forcing a scan](https://github.com/LeastAuthority/magic-folder/pull/463): I expected that telling the software to "scan for changes now" also entailed "_and_ immediately upload any new changes" but, by your description here, it seems this is not the case (i.e., that "scanning" merely creates local snapshots). Good to know. If there as an API to "create local snapshots now", perhaps there should also be one to "immediately upload any new changes"? In any case, a "create local snapshots" endpoint seems to be of pretty marginal utility in absence of the ability to also force uploads. As far as I can tell, there's no way for an external application to tell Magic-Folder to perform an upload _now_ (beyond, say, drastically lowering `poll-interval` such that "now" is "every second").

>I do agree that how the log is presented looks like it may be something failing.

Would you consider this expected (or even desired) also? I'm wondering how a reader of these logs is supposed to distinguish between "an error that suggests a problem with the software" versus "an error that is being used for flow-control by some other component/codepath".

**Comment by tomprince** [comment]
> > That is more or less expected behavior, though perhaps not desired.
> 
> "Expected" for the developers of this project, perhaps, [...]

Yes. It would probably make sense to trigger upload as soon as we've snapshotted a file. I definitely view doing that as QoL improvement, rather than a blocker for the initial realse, though.

> 
> > We take local snapshots as we discover them, and then periodically upload them as a separate task. It looks like poll-interval currently controls how often we look for uploads to do.
> 
> Thank you for explaining this. [...]

I think the main reason the endpoint to create local snapshots exists is because that code was written before we could scan, and so we needed a way to test that code. It currently doesn't do anything like check if the file has even changed, before making a snapshot.

We could definitely add more APIs for triggering different things (we don't currently have a way to trigger scanning peers either). That said, I also think magic-folder should just work, and I am a little reluctant to expose all kinds of different knobs to control things (particularly if it might end up constraining us changing how we breakup the loops we have).

> > I do agree that how the log is presented looks like it may be something failing.
> 
> Would you consider this expected (or even desired) also?

The logs are definitely aimed at developers primarily; any errors for users should be reported via the API in some fashion. I don't have strong feelings about how this is represented, but I definitely think we should err on the side of developer convenience for writing logging code (at least at the moment). For example, for a function that can raise an exception in normal operation, representing that as a failing action is the natural thing to write.

I will say, that unexpected failures tend to include a traceback (which the errors above don't). We aren't currently consistent about this (and sometimes we write them to stdout instead); I would consider it a bug if we have places where we don't do that. I have a couple of PRs open that incidentally do this for a couple of places where we currently print a traceback.

**Comment by meejah** [comment]
I think it definitely makes sense to start uploading things sooner than happens currently.
