### ISSUE TITLE
`magic-folder-api` fails with "Error: invalid port 0" when global configuration uses tcp endpoint with port number0

### ISSUE THREAD

**Issue by exarkun** [LeastAuthority/magic-folder#516]
When `magic-folder-api` is pointed at a configuration that is configured with a TCP endpoint address using port 0 (for OS-managed automatic free port assignment) it fails to operate, reporting only:

```
Error: invalid port 0
```

In this case a running magic-folder process will be listening on *some* actual TCP port number of `magic-folder-api` is not figuring out what this is.

The expected behavior is that wherever the running magic-folder process is listening, `magic-folder-api` can find it to invoke APIs.

**Comment by meejah** [comment]
Probably short-term we should disallow use of `tcp:0` as a listening-string. That is, treat the use-case of "magic-folder picks a port for me" as a future enhancement...?

(Basically every `magic-folder` and `magic-folder-api` command will fail in this case, I assume...)

**Comment by exarkun** [comment]
> Probably short-term we should disallow use of tcp:0 as a listening-string. That is, treat the use-case of "magic-folder picks a port for me" as a future enhancement...?

Since that will break the current efforts to integrate with GridSync I don't think that's a great step.  Let's not take any steps in that direction until we know what the big-picture integration plan looks like.

**Comment by meejah** [comment]
I thought basically everything is broken if you do `tcp:0`..?

**Comment by exarkun** [comment]
@crwood managed to get GridSync talking to magic-folder in this configuration *somehow* (I'm guessing by scraping "Blahblah listening on port ..." from stdout but I dunno for sure).

**Comment by meejah** [comment]
Hmm, okay .. I guess on the down-side that means none of the CLI etc tools will work (but I suppose also users aren't supposed to be touching that, so it'll just affect us devs and/or support).

Just in case it's not clear: my proposed interim solution above was just to have GridSync hard-code a port. Obviously that has certain downsides, but at least it's explicit. (And it has the _advantage_ that trying to start a second magic-folder instance accidentally will fail right away .. which is good because like Highlander there  should be only one). And of course "scraping stdout" sucks.

**Comment by tomprince** [comment]
> [...] And it has the _advantage_ that trying to start a second magic-folder instance accidentally will fail right away .. which is good because like Highlander there should be only one [...]

It actually appears that it *doesn't* currently fail, even if we fail to start the http api.
