### ISSUE TITLE
Provide "uploaded time" in status

### ISSUE THREAD

**Issue by meejah** [LeastAuthority/magic-folder#523]
To communicate when a file was last uploaded, a timestamp should be included when the last upload finished.

**Comment by meejah** [comment]
Actually, according to code (and subsequent manual tests) the `last-updated` time already reflects the uploaded time. The last-updated time is changed whenever any change is recorded (so "queued a local snapshot" or "uploaded to Personal DMD" will both change the "last updated" timestamp).

So you can say if a file is up-to-date and when it was last changed: if the relative-path is in `uploads` (or `downloads`) then there are changes pending. The most-recent upload (or download) time is reflected in `last-updated` timestamp.

A locally-changed (or created) file will go through states:

- in "uploads" list, with `queued-at` time (only)
- in "uploads" list, with `queued-at` and `started-at` timestamps
- gone from "uploads" list, present in "recent" list (with `last-updated` time being shortly after the Personal DMD entry was updated)

**Comment by tomprince** [comment]
I will note that we record that timestamp *before* we link the snapshot cap into the personal DMD, which effectively means that it doesn't mean the file is persistent on-grid. I guess the file will still be reported as an upload in the status in that case[1], so if it isn't in the uploads list, the time will be (hopefully only) shortly before it is linked to the DMD. That said, I think if we want to report the time when we linked the cap into the DMD, we should record that time explicitly (particularly if we end up doing something like https://github.com/LeastAuthority/magic-folder/pull/471).


(Ignoring what happens when we restart)

**Comment by meejah** [comment]
If we're being pedantic: the time is currently noted _after_ the upload takes place. Thus, it is "on the grid".

It is true that it is _not_ linked in the DMD at this point. We could certainly easily update the timestamp again at that point if its interesting -- but UIs have no way to distinguish which timestamp they're seeing anyway.
